apiVersion: v1
kind: Service
metadata: 
  name: sokios-service
  namespace: sokios
spec: 
  type: NodePort
  selector: 
    app: sokios-app
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8080